### PR TITLE
fix (dependencies) whitelist new modules

### PR DESCRIPTION
**Pull request by ivanpankov**

### CODE REVIEW

**Comment by kalinkrustev** [comment]
There are number of things that stop me from merging this.
I am on the edge of deciding for a separate tool - something like dw-tools.

Some of my worries:
- `@date-io/date-fns` - we already allowed usage of `date-fns`, so this is alternative, which prepackages a fixed set of functions
- "eslint-config-airbnb": "^18.0.1",  "eslint-config-prettier": "^6.4.0" - we already have lint rules. I do not like the idea to have alternative rules, this increases efforts to manage two different approaches
- "@jsonforms/core": "^2.3.1",  "@jsonforms/react": "^2.3.1" - we already use react-jsonschema-form, so we have again 2 alternatives

There are also few other considerations.
@zetxx , @stambata - what do you think? Shall we go for dw-tools or keep complicating ut-tools?

**Comment by ivanpankov** [comment]
Hi all,

I suspect that you might not up-to-date because of bad communication so let me inform you about couple of packages.

Firstly of all it is ut-front-material or our standard library. It is made on top of material-ui v.4  and React 16 and support material-ui theming (means we have extracted theme that should match company design).
Note that this library is widely used from other developers in projects.
ut-front-material uses material-ui-pickers for date picker which requires  @date-io/date-fns, and date-fns.
@date-io/date-fns is actually abstraction layer over multiple date libraries including date-fns (see documentation https://github.com/dmtrKovalenko/date-io) so IMHO I think we need this library.
Link to storybook https://ut-front-material-storybook.netlify.com/?path=/story/components-input-control--input-control

Secondly it is wave-ui-registry. It is set of components for jsonforms.io. It is made on top of ut-front-material and requires @jsonforms/core and @jsonforms/react.
Why we are using jsonforms instead of react-jsonschema-form? There where some discussions here in the office.
https://confluence.softwaregroup.com/display/RD/2019-07-10+Meeting+Notes
https://confluence.softwaregroup.com/display/UPWS/2019-05-20+Meeting+notes
The main issues I was facing is that  react-jsonschema-form:

  *   it puts every input control in DIV wrapper which make impossible to do complex layouts.
  *   There were no debouncing of inputs which cause lagging in big forms.
  *   Components or "registry" in build inside library. You can override with external components but you can't remove them from library.
  *   Existing components are not build on top of standard libraries. You have to support both react-jsonschema-form and ut-front-material in separate way.

Link to storybook of new components for jsonforms.io: https://wave-ui-registry.netlify.com/?path=/story/controls--boolean

Thirdly is ut-taskmanagement . You can thing of this as front-end of workflow service. It is a project I initially started to work on. Actually for this project I need ut-front-material and wave-ui-registry so I had to start to work on and support last two packages.

Now about current situation.
I was given a boiler plate to start with. As I understand it is not compatible with current ut-tool rules so I have to manage to fix it in all three packages ut-front-material, wave-ui-registry and ut-taskmanagement.

In order to do this I guess we have to update ut-tools. Also if we want to use ut-react or whatever name it was (sorry cant remember the name) we maybe should update it to v.15. Currently it uses v.15.

I will remove  eslint-config-airbnb": "^18.0.1" and "eslint-config-prettier". They are leftover from boilerplate I used.

Keep in mind that we try to move packages now:

  *
wave/wave-ui-registry now become dw/lib/lib-ui-registry
  *
<https://git.softwaregroup.com/dw/standard/standard-service-taskmanagement> dw/standard/standard-service-taskmanagement now become  ut5/ut-taskmanagement




________________________________

**Comment by kalinkrustev** [comment]
Further issues are:
* Some of the dependencies are not in the proper places. The idea of peerDevDependencies is that modules (the ones prefixed ut-) should specify react and related dependencies (such as redux, component libraries, etc.) as peerDependencies and implementations (the ones prefixed with ut-) should specify them as devDependencies.
* As some of dw modules tried to be fancy and not follow the simple rules to be prefixed with ut- or impl-, this now complicates ut-tools and wastes time to specify exceptions of rules, etc. For example the mentioned wave-ui-registry's package.json cannot be linted, as ut-tools only expects two kinds of prefixes. 

That's why I was thinking dw needs to fork ut-tools and people behind these naming ideas start supporting their own tool. The idea of having a white list is to stop having 2 alternatives for the same thing, like json shchema form, fn-date, etc. Now we have bloated dependencies and it is not clear who will consolidate the two approaches. So trying to plug-in these rules when things were already developed, breaks the idea of whitelisting, as we are forced to whitelist exactly what we wanted to avoid. 

Also it is not clear to me why we need wave-ui-registry. I think the idea is to put the components in ut-front-material.

@stambata , @zetxx any comments?

**Comment by stambata** [comment]
I don't really have any constructive comments to be honest. All the concerns referred in this discussion are valid. I myself tried to extend the supported repository name patterns twice already but there are still variations that are not supported. I am not sure if I want to add more. They all have to be whitelisted too at some point... so I kind of agree that all this bloats the tool as we have modules, implementations, solution controllers, standard services, custom services, ui services, service portals, libraries, etc... and the complexity grows gradually. When the exceptions become too many it gets obvious that there is something wrong. But on the other hand there was too much effort put in this tool during the years and I am not sure how feasible would be to develop something similar in parralel - it's too complex. Maybe we need to classify all concerns and take a decision based on that. Reinventing everything this tool does would be a waste in my opinion.

**Comment by pkande** [comment]
We should avoid to re-inviting what ut-tools does. Instead, we should adapt it as we are evolving.
Making a second tool is definitely no the way to go.
Initially our rule was based on prefix ut* and impl* in order to apply a given policies, as you can see, this is no longer applicable.
 File naming is basically used for better classification or categorization  and is to be consistent and descriptive.
What is the reason to limit eslint with file prefixed with ut* or impl*? And now I see we add dw* to the list, this is getting more complete; do we have any practical reasons?

**Comment by kalinkrustev** [comment]
whitelist was moved to another repo

**Pull request closed without merging**
