### PR TITLE
WIP: Fix: Dev Deps node-cardcrypto: 1.0.2

### PR DESCRIPTION
**Pull request by beyrul**
For ut-iso-acquirer-simulator

### CODE REVIEW

**Comment by kalinkrustev** [comment]
Can somebody review this module. It is not very popular and we need to be careful to not end with some malware. Do not just look in github, as npm package can contain different code.

**Comment by Kristiyan-Todorov** [comment]
Except for this [any version dependency], the npm package seems clear of any suspicious code

[any version dependency]: https://github.com/coolbong/node-cardcrypto/blob/master/package.json#L28

**Comment by kalinkrustev** [comment]
Let's discuss next week. I can't understand what this module brings on top of node crypto.

**Comment by beyrul** [comment]
Used node crypto in flow instead of node-cardcrypto .

**Pull request closed without merging**
